"""empty message

Revision ID: 514edd2c7ee1
Revises: f17a8c2d9b40
Create Date: 2026-10-05 14:08:34.958996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514edd2c7ee1'
down_revision = 'f17a8c2d9b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
